### ISSUE TITLE
Crashes when being invited

### ISSUE THREAD

**Issue by KraXarN** [scholtzm/node-steam-groups#3]
Crashes when being invited:

/home/kraxarn/node_modules/steam-groups/node_modules/bytebuffer/dist/ByteBufferNB.js:2181
                throw TypeError("Illegal begin: Not an integer");
                      ^
TypeError: Illegal begin: Not an integer
    at TypeError (<anonymous>)
    at module.exports.ByteBufferPrototype.copy (/home/kraxarn/node_modules/steam-groups/node_mod
ules/bytebuffer/dist/ByteBufferNB.js:2181:23)
    at Function.Buffer.concat (buffer.js:499:9)
    at SteamClient._send (/home/kraxarn/node_modules/steam/lib/steam_client.js:70:32)
    at SteamClient.prototype.acceptGroup (/home/kraxarn/node_modules/steam-groups/index.js:17:14
)
    at SteamClient.bot.on.name (/home/kraxarn/steambot/node-steam.js:132:7)
    at SteamClient.emit (events.js:98:17)
    at SteamClient.<anonymous> (/home/kraxarn/node_modules/steam/lib/handlers/friends.js:179:12)
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (/home/kraxarn/node_modules/steam/lib/handlers/
friends.js:175:32)

My code is:

bot.on('group', function(steamID, relationship) {
	console.log("[S] Group event for " + steamID + " type " + relationship);
	if (relationship == Steam.EClanRelationship.Invited) {
		console.log("[S] Joined group " + steamID);
		bot.acceptGroup(steamID);
	}
});

**Comment by scholtzm** [comment]
I will test it out ASAP.

**Comment by KraXarN** [comment]
Spent a long time updating node and then steam-node, but it works fine now! Thanks, didn't know there was an update to it :p
